- name: Create K8s Hard-Way VMs on libvirt (Ansible-only)
  hosts: localhost
  gather_facts: false
  vars_files: ['../vars/vms.yml']
  collections: [community.libvirt]
  vars:
    ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    libvirt_pool: default
    libvirt_uri: "qemu:///system"
    pool_dir: "/var/lib/libvirt/images"

  tasks: 
    - name: Ensure pool directory exists
      become: true
      file:
        path: "{{ pool_dir }}"
        state: directory
        mode: "0755"

    - name: List existing pools (system URI)
      community.libvirt.virt_pool:
        command: list_pools
        uri: "{{ libvirt_uri }}"
      register: pools

    - name: Define dir pool if missing (idempotent)
      community.libvirt.virt_pool:
        command: define
        uri: "{{ libvirt_uri }}"
        xml: |
          <pool type='dir'>
            <name>{{ libvirt_pool }}</name>
            <target><path>{{ pool_dir }}</path></target>
          </pool>
      when: libvirt_pool not in (pools.pools | default([]))

    - name: Start pool
      community.libvirt.virt_pool:
        name: "{{ libvirt_pool }}"
        command: start
        uri: "{{ libvirt_uri }}"

    - name: Autostart pool
      community.libvirt.virt_pool:
        name: "{{ libvirt_pool }}"
        command: autostart
        uri: "{{ libvirt_uri }}"   

    - name: Ensure cloud image present
      get_url:
        url: "{{ image_url }}"
        dest: "../images/jammy.qcow2"
        mode: "0644"

    - name: Refresh storage pool
      community.libvirt.virt_pool:
        name: "{{ libvirt_pool }}"
        command: refresh

    - name: Get pool XML
      command: "virsh pool-dumpxml {{ libvirt_pool }}"
      register: pool_xml
      changed_when: false

    - name: Extract pool path
      set_fact:
        pool_path: "{{ pool_xml.stdout | regex_search('<path>(.*?)</path>', '\\1') }}"

    - name: Create qcow2 volumes with backing (libvirt XML)
      community.libvirt.virt_volume:
        pool: "{{ libvirt_pool }}"
        state: present
        xml: |
          <volume type='file'>
            <name>{{ item.name }}.qcow2</name>
            <capacity unit='G'>{{ item.disk_gb }}</capacity>
            <target>
              <format type='qcow2'/>
            </target>
            <backingStore type='file'>
              <path>{{ (playbook_dir + '/../images/jammy.qcow2') | realpath }}</path>
              <format type='qcow2'/>
            </backingStore>
          </volume>
      loop: "{{ vms }}"

    - name: Render cloud-init user-data
      template:
        src: "../cloudinit/user-data.tpl"
        dest: "../cloudinit/{{ item.name }}-user-data"
      loop: "{{ vms }}"
      vars:
        name: "{{ item.name }}"
        ssh_key: "{{ ssh_key | default('') }}"

    - name: Render cloud-init network-config
      template:
        src: "../cloudinit/network-config.tpl"
        dest: "../cloudinit/{{ item.name }}-network-config"
      loop: "{{ vms }}"
      vars:
        ip: "{{ item.ip }}"
        gw: "{{ item.gw }}"
        dns: "{{ item.dns }}"

    - name: Create CIDATA CDROM via libvirt
      community.libvirt.virt_volume:
        pool: "{{ libvirt_pool }}"
        command: create_cidata_cdrom
        name: "{{ item.name }}-seed.iso"
        cloudinit_config:
          USERDATA: "{{ lookup('file', playbook_dir + '/../cloudinit/' + item.name + '-user-data') }}"
          NETWORK_CONFIG: "{{ lookup('file', playbook_dir + '/../cloudinit/' + item.name + '-network-config') }}"
      loop: "{{ vms }}"

    - name: Define and start VMs
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: running
        autostart: true
        memory_mb: "{{ item.mem_mb }}"
        vcpus: "{{ item.vcpus }}"
        networks:
          - network: "{{ libvirt_network }}"
        disks:
          - type: file
            device: disk
            path: "{{ pool_path }}/{{ item.name }}.qcow2"
            format: qcow2
          - type: file
            device: cdrom
            path: "{{ pool_path }}/{{ item.name }}-seed.iso"
        boot: hd,cdrom
        graphics: none
        os_type: linux
        arch: x86_64
      loop: "{{ vms }}"

    - name: Wait for SSH on each VM
      wait_for:
        host: "{{ item.ip.split('/')[0] }}"
        port: 22
        timeout: 300
      loop: "{{ vms }}"
