# --- Preflight: Reachability 
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
  tasks:
    - name: Wait for SSH
      wait_for:
        port: 22
        host: "{{ ansible_host | default(inventory_hostname) }}"
        timeout: 300
      delegate_to: localhost
    - name: Collect facts
      setup:

# --- base os
- hosts: all
  become: true
  any_errors_fatal: true
  roles:
    - role: base-os    # sysctls, /etc/hosts, DNS/Resolver
    - role: comfort    # tmux.conf, vimrc (optional)
    - role: tools      # cert_verify.sh (optional)